# 这些是支持的资金平台。GitHub 将在您的个人资料上创建一个赞助按钮，链接到您的赞助页面。

# 如果您有 GitHub Sponsors，请取消注释下面的行
# github: abtree-team

# 如果您有 Open Collective，请取消注释下面的行
# open_collective: abtree

# 如果您有 Ko-fi，请取消注释下面的行
# ko_fi: abtree

# 如果您有 Tidelift，请取消注释下面的行
# tidelift: abtree

# 如果您有 Community Bridge，请取消注释下面的行
# community_bridge: abtree

# 如果您有 Liberapay，请取消注释下面的行
# liberapay: abtree

# 如果您有 IssueHunt，请取消注释下面的行
# issuehunt: abtree

# 如果您有 Otechie，请取消注释下面的行
# otechie: abtree

# 如果您有 Custom，请取消注释下面的行
# custom: https://www.paypal.me/abtree 