name: Bug Report
description: Report a Bug
title: "[BUG] "
labels: ["bug"]
assignees:
  - "abtree-team"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a Bug! Please fill in the following information to help us better resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly and concisely describe this bug
      placeholder: Describe what this bug is...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce this bug
      placeholder: |
        1. Run '...'
        2. Click '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to see
      placeholder: Should display...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actually displays...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: ABTree Version
      description: The ABTree version you are using
      options:
        - "0.1.0"
        - "Development Version"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: python
    attributes:
      label: Python Version
      description: The Python version you are using
      options:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Your operating system
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If possible, please provide a code example that reproduces the bug
      placeholder: |
        ```python
        # Your code example
        ```

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If there are error logs, please paste them here
      placeholder: |
        ```
        Error log content
        ```

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following items
      options:
        - label: I have searched existing Issues and confirmed this bug has not been reported
        - label: I have tried the latest development version
        - label: I have provided complete information to reproduce this bug 