name: Feature Request
description: 请求一个新功能
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - "abtree-team"

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能请求！请填写以下信息以帮助我们更好地理解您的需求。

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 清晰简洁地描述您想要的功能
      placeholder: 描述您想要的功能...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 动机
      description: 为什么需要这个功能？它解决了什么问题？
      placeholder: 这个功能将帮助我...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景
      description: 描述这个功能的使用场景
      placeholder: 当用户...时，这个功能将...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您是否考虑过其他解决方案？
      placeholder: 我考虑过...，但是...

  - type: textarea
    id: implementation
    attributes:
      label: 实现建议
      description: 如果您有实现建议，请描述一下
      placeholder: 可能的实现方式...

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 请确认以下项目
      options:
        - label: 我已经搜索了现有的 Issues，确认这个功能还没有被请求
        - label: 这个功能与 ABTree 的目标一致
        - label: 我提供了详细的功能描述和使用场景 